class Collector {
  Map<String, List<bool>> data = {
    "paintDot": [],
    "paintUpMonochromatic": [],
    "paintDownMonochromatic": [],
    "paintLeftMonochromatic": [],
    "paintRightMonochromatic": [],
    "paintSquareMonochromatic": [],
    "paintDiagonalUpLeftMonochromatic": [],
    "paintDiagonalUpRightMonochromatic": [],
    "paintDiagonalDownLeftMonochromatic": [],
    "paintDiagonalDownRightMonochromatic": [],
    "paintLUpLeftMonochromatic": [],
    "paintLUpRightMonochromatic": [],
    "paintLDownLeftMonochromatic": [],
    "paintLDownRightMonochromatic": [],
    "paintLLeftUpMonochromatic": [],
    "paintLLeftDownMonochromatic": [],
    "paintLRightUpMonochromatic": [],
    "paintLRightDownMonochromatic": [],
    "paintZigzagLeftUpDownMonochromatic": [],
    "paintZigzagLeftDownUpMonochromatic": [],
    "paintZigzagRightUpDownMonochromatic": [],
    "paintZigzagRightDownUpMonochromatic": [],
    "paintZigzagUpLeftRightMonochromatic": [],
    "paintZigzagUpRightLeftMonochromatic": [],
    "paintZigzagDownLeftRightMonochromatic": [],
    "paintZigzagDownRightLeftMonochromatic": [],
    "paintUpPolychromatic": [],
    "paintDownPolychromatic": [],
    "paintLeftPolychromatic": [],
    "paintRightPolychromatic": [],
    "paintSquarePolychromatic": [],
    "paintDiagonalUpLeftPolychromatic": [],
    "paintDiagonalUpRightPolychromatic": [],
    "paintDiagonalDownLeftPolychromatic": [],
    "paintDiagonalDownRightPolychromatic": [],
    "paintLUpLeftPolychromatic": [],
    "paintLUpRightPolychromatic": [],
    "paintLDownLeftPolychromatic": [],
    "paintLDownRightPolychromatic": [],
    "paintLLeftUpPolychromatic": [],
    "paintLLeftDownPolychromatic": [],
    "paintLRightUpPolychromatic": [],
    "paintLRightDownPolychromatic": [],
    "paintZigzagLeftUpDownPolychromatic": [],
    "paintZigzagLeftDownUpPolychromatic": [],
    "paintZigzagRightUpDownPolychromatic": [],
    "paintZigzagRightDownUpPolychromatic": [],
    "paintZigzagUpLeftRightPolychromatic": [],
    "paintZigzagUpRightLeftPolychromatic": [],
    "paintZigzagDownLeftRightPolychromatic": [],
    "paintZigzagDownRightLeftPolychromatic": [],
    "fillEmpty": [],
    "copy": [],
    "mirrorVertical": [],
    "mirrorHorizontal": [],
  };

  @override
  String toString() => data.toString();
}
