name: CodeCov

on: [push]

jobs:
  codeCov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Restore packages
        run: flutter pub get
        
      - name: Run tests with coverage
        run: pub run test --coverage="coverage"
      - name: Convert coverage to ICOV
        run: pub run coverage:format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.packages --report-on=lib
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1.0.2
        with:
          token: 6f44335c-cb76-4436-a38b-c6086b51ef04
          file: coverage.lcov
